const REGEXP_ONLY_DIGITS = /^[0-9]+$/
const REGEXP_ONLY_CHARS = /^[a-zA-Z]+$/
const REGEXP_ONLY_DIGITS_AND_CHARS = /^[a-zA-Z0-9]+$/

export { REGEXP_ONLY_DIGITS, REGEXP_ONLY_CHARS, REGEXP_ONLY_DIGITS_AND_CHARS }